APPLICATION = test-hdc3020-auto
BOARD ?= l21-alone

BASE ?= $(CURDIR)/../
LORA3ABASE ?= $(BASE)/lora3a-boards
RIOTBASE ?= $(BASE)/RIOT

EXTERNAL_BOARD_DIRS=$(LORA3ABASE)/boards
EXTERNAL_MODULE_DIRS+=$(LORA3ABASE)/modules
EXTERNAL_PKG_DIRS=$(LORA3ABASE)/pkg

DEVELHELP ?= 1
QUIET ?= 1
PORT ?= /dev/ttyUSB0

AUTO ?= 1
SLEEP ?= 30

USEMODULE += hdc3020
USEMODULE += printf_float
USEMODULE += ztimer_msec

#CFLAGS += -DACME0_BUS_MODE=MODE_I2C -DACME0_I2C_SPEED=I2C_SPEED_FAST
#CFLAGS += -DACME2_BUS_MODE=MODE_I2C -DACME2_I2C_SPEED=I2C_SPEED_FAST
CFLAGS += -DACME0_BUS_MODE=MODE_I2C -DACME0_I2C_SPEED=I2C_SPEED_NORMAL
CFLAGS += -DACME2_BUS_MODE=MODE_I2C -DACME2_I2C_SPEED=I2C_SPEED_NORMAL

HDC3020_SENSORS := "{.i2c_dev=ACME0_I2C_DEV,.i2c_addr=HDC3020_PARAM_I2C_ADDR,.enable_pin=HDC3020_ENABLE_PIN,.enable_on=HDC3020_ENABLE_ON,.start_delay=HDC3020_START_DELAY,.measure_delay=HDC3020_MEAS_DELAY},"
HDC3020_SENSORS += "{.i2c_dev=ACME2_I2C_DEV,.i2c_addr=HDC3020_PARAM_I2C_ADDR,.enable_pin=HDC3020_ENABLE_PIN,.enable_on=HDC3020_ENABLE_ON,.start_delay=HDC3020_START_DELAY,.measure_delay=HDC3020_MEAS_DELAY}"

CFLAGS += -DHDC3020_PARAMS="$(HDC3020_SENSORS)"

ifeq (1, $(AUTO))
    CFLAGS += -DAUTO_MEASURE
endif
CFLAGS += -DSLEEP_SECS=$(SLEEP)

include $(RIOTBASE)/Makefile.include
include $(LORA3ABASE)/Makefile.include
